### ISSUE TITLE
Switch not aesthetically pleasing while on dark background

### ISSUE THREAD

**Issue by grounded042** [designmodo/Flat-UI#119]
When using a switch on a dark background, it shows some gray on the right side while in the "ON" position. 

![2014-03-04 12_48_35-clipboard](https://f.cloud.github.com/assets/1075622/2324144/8dffe8ea-a3c5-11e3-9f66-908234151430.png)

I suggest doing one of the following to fix it. (The first gives me better results but can have an unwanted side effect when dragging the switch instead of clicking.)

1) Add: 

``` css
.has-switch .switch-on span.switch-right {
    -webkit-transition: all 0s ease 0.25s;
    transition: all 0s ease 0.25s;
    background-color: transparent;
}

.has-switch span.switch-right {
    -webkit-transition: all 0s;
    transition: all 0s; 
}
```

2) Change this block (starting at line 3515 as of 00a8e14948593d6ef3b3656b2c79d8b432914168) from :

``` css
.has-switch > div.switch-on {
  left: 0;
}
```

to:

``` css
.has-switch > div.switch-on {
  left: 1px;
}
```
