### ISSUE TITLE
Input Icons in Horizontal Form Grid Overlapping Input Border

### ISSUE THREAD

**Issue by fursid** [designmodo/Flat-UI#126]
The input box icons (in form.form-horizontal with grid columns for label & input boxes) are overlapping the input border. 

The temporary fix I've applied for this is to add the following CSS rule:

``` CSS
.form-horizontal [class^="col-"]  .input-icon,
.form-horizontal [class*=" col-"]  .input-icon { right: 17px;  }
```

Sample Code:

``` HTML
<div class="form-group">
  <label for="exmpleInput" class="col-sm-4 control-label">Input Label</label>
  <div class="col-sm-8">
    <input type="text" id="exmpleInput" class="form-control" placeholder="Placeholder text">
    <span class="input-icon fui-info"></span>
  </div>
</div>
```

Image:
![image](https://cloud.githubusercontent.com/assets/563015/2588374/58a3cb14-ba39-11e3-85a1-1234af1e546a.png)
