### ISSUE TITLE
Proposed helper classes for huge margin/padding .mha, .pha

### ISSUE THREAD

**Issue by fursid** [designmodo/Flat-UI#128]
Proposed helper classes for huge margin/padding (40px):

``` CSS
/* Spacing Helper Classes*/
.pth, .pvh, .pah {padding-top: 40px !important; }
.prh, .phh, .pah {padding-right: 40px !important; }
.pbh, .pvh, .pah {padding-bottom: 40px !important; }
.plh, .phh, .pah {padding-left: 40px !important; }

.mth, .mvh, .mah {margin-top: 40px !important; }
.mrh, .mhh, .mah {margin-right: 40px !important; }
.mbh, .mvh, .mah {margin-bottom: 40px !important; }
.mlh, .mhh, .mah {margin-left: 40px !important; }
```
