### ISSUE TITLE
Invalid CSS "-webkit-transform: scale(1.001, );" at line 988

### ISSUE THREAD

**Issue by evolve2k** [designmodo/Flat-UI#131]
When loading flat-ui into Rails 4 it generates the error: Invalid CSS at line 988.
As a start I've copied flat-ui.css into /vendor/assets/stylesheets and my test generate this error.

The errenous code is:

``` css
.caret {
  border-width: 8px 6px;
  border-bottom-color: #34495e;
  border-top-color: #34495e;
  border-style: solid;
  border-bottom-style: none;
  -webkit-transition: 0.25s;
  transition: 0.25s;
  -webkit-transform: scale(1.001, );   <===== ERROR HERE LINE 988
  -ms-transform: scale(1.001, );      
  transform: scale(1.001, );
}
```

I removed the trailing commas on this line and the next two lines as well and the error went away. 
Suggest this is the fix unless there is a reason those trailing commas **should** be there?
