### ISSUE TITLE
Navbar search form border 

### ISSUE THREAD

**Issue by BirdSK** [designmodo/Flat-UI#181]
Hi,
when i use search form, i dont get that green border line around whole element(see [image](https://cloud.githubusercontent.com/assets/11062472/6251176/b88fe4d4-b792-11e4-8d17-c7cc34d73226.jpg)). I don't know where is mistake, because i copy source code straight from documentation http://designmodo.github.io/Flat-UI/docs/components.html issue persist in every browser i tried.
Any ideas ? 
Thanks.

**Comment by BirdSK** [comment]
oh, and i dont want to open another issue, but how to change button color in navbar ? when i replace class btn-default with for example btn-dange, nothing changes. It works perfectly outside of navbar. Thanks

**Comment by bonniejools** [comment]
@BirdSK +1 I have also had this issue

**Comment by sepehr** [comment]
I second this.

**Comment by tartinesKiller** [comment]
Same here, maybe a dependency that differ, I guess... 
![screenshot at 09-26-38](https://cloud.githubusercontent.com/assets/12556339/8226124/2a7dd206-159c-11e5-96d7-ef9c5af83aaf.png)

**Comment by MMTLukas** [comment]
+1

**Comment by dozij** [comment]
+1

**Comment by StefanYohansson** [comment]
can someone send a plnkr with this behavior? I can't reproduce it here.

**Comment by bonniejools** [comment]
I finally bothered to get round to looking up the solution to this. You have to add the `focus` to the `input-group` class containing search box and then remove it when focus disappears. The code used in the examples page is:

    $('.input-group').on('focus', '.form-control', function () {
      $(this).closest('.input-group, .form-group').addClass('focus');
    }).on('blur', '.form-control', function () {
      $(this).closest('.input-group, .form-group').removeClass('focus');
    });

and the html is

    <div class="input-group">
      <input type="text" class="form-control" placeholder="Search" id="search-query-3">
      <span class="input-group-btn">
        <button type="submit" class="btn"><span class="fui-search"></span></button>
      </span>
    </div>

This isn't really mentionned in the docs (if it is then I must have missed it). Can @StefanYohansson confirm whether it is or not. Perhaps I can create a pull request for the documentation page.

**Comment by StefanYohansson** [comment]
Yes @bonniejools It's the "right solution".
Unfortunately CSS can't select predecessor nodes. So there's a way to style `.input-group-btn` if this class appears after `.form-control`:
```html
<div class="input-group">
  <input type="text" class="form-control" placeholder="Search" id="search-query-3">
  <span class="input-group-btn">
    <button type="submit" class="btn"><span class="fui-search"></span></button>
  </span>
</div>
```

using a selector like this:
```less
// Focus State
// -------------------------
.form-group,
.input-group {
   .form-control:focus + .input-group-addon {
     background-color: @brand-secondary;
     border-color: @brand-secondary;
   }
   .form-control:focus + .input-group-btn {
   > .btn-default + .btn-default {
      border-left-color: mix(@brand-secondary, black, 85%);
    }
    .btn {
      border-color: @brand-secondary;
      background-color: @inverse;
      color: @brand-secondary;
    }
    .btn-default {
      .button-variant(@btn-default-color, @brand-secondary, @btn-primary-hover-bg, @btn-primary-active-bg);
    }
  }
}
```

but this can't solve the problem when `.input-group-btn` appears before `.form-control`.

```html
<div class="input-group input-group-hg input-group-rounded">
  <span class="input-group-btn">
    <button type="submit" class="btn"><span class="fui-search"></span></button>
  </span>
  <input type="text" class="form-control" placeholder="Search" id="search-query-2">
</div>
```

so, i think it's the reason why Flat-UI developers written a javascript for this and used a "focus" class in wrapper.

maybe when browsers implements this proposal (has proposal) https://drafts.csswg.org/selectors-4/#relational. Someone can fix this using only CSS.
