### ISSUE TITLE
Flat-UI-Pro-Icons Glyph was incorrect in the Firefox console

### ISSUE THREAD

**Issue by fangminglee** [designmodo/Flat-UI#294]
## Bug description

When using Flat-UI with Firefox, I'm seeing many warnings about font in the console.

### For example:
```shell
downloadable font: OS/2: Bad sTypoLineGap, setting it to 0: -64 (font-family: "Flat-UI-Pro-Icons" style:normal weight:400 stretch:100 src index:0)
downloadable font: Glyph bbox was incorrect (glyph ids 13 14 23 26 41 42 44 50 52 58 63 69 70 71 73 75 76 79 81 83 86 87 88 89 90 92 94 97 99 100) (font-family: "Flat-UI-Pro-Icons" style:normal weight:400 stretch:100 src index:0)
```

#### I guess it might be the font

```css
@font-face {
  font-family: "Flat-UI-Pro-Icons";
  src: url("/font/flatui/glyphicons/flat-ui-pro-icons-regular.eot");
  src: url("/font/flatui/glyphicons/flat-ui-pro-icons-regular.eot?#iefix") format("embedded-opentype"),url("/font/flatui/glyphicons/flat-ui-pro-icons-regular.woff") format("woff"),url("/font/flatui/glyphicons/flat-ui-pro-icons-regular.ttf") format("truetype"),url("/font/flatui/glyphicons/flat-ui-pro-icons-regular.svg#flat-ui-pro-icons-regular") format("svg");
  font-weight: normal;
  font-style: normal;
}
```
Here is my way I use it
