### ISSUE TITLE
Typography/header sizes are 'off' between free and pro

### ISSUE THREAD

**Issue by iurevych** [designmodo/Flat-UI#49]
Hi, I've got Pro, and have noticed that the fonts sizes are quite different between the pro and the free. On the demo page http://designmodo.github.io/Flat-UI/ for instance an h6 is:

``` css
h6 {
font-size: 13px;
font-weight: 500;
text-transform: uppercase;
}
```

but on the pro version I use on my site these are coming from flat-ui.css

``` css
h6 {
font-weight: normal;
}
h1, .h1, h2, .h2, h3, .h3, h4, .h4, h5, .h5, h6, .h6 {
line-height: 1.2em;
}
h6, .h6 {
font-size: 23.996px /* 24px */;
}
```
